version: "3"

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data      
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${PG_DB} -U $${PG_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: sh -c "python3 manage.py migrate
      && python3 manage.py loaddata data/data_posts.json
      && python3 manage.py loaddata data/data_users.json
      && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO -P eventlet 
    env_file:
      - .env
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    env_file:
      - .env
    depends_on:
      - redis
      - app

volumes:
  pg_data: